POC i18n
fewlinesco/connect-account pull request #666
Opened 2021-06-07 11:54 UTC by Fuzznimp

## Description

## Type of change

- [ ] **Chore** (non-breaking change which refactors / improves the existing code base).
- [ ] **Bug fix** (non-breaking change which fixes an issue).
- [ ] **New feature** (non-breaking change which adds functionality).
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected).

## Issues

## List of added dependencies

## Screenshots

## Checklist

- [ ] My code follows the style [**contributing guidelines**][contributing_file] of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.

[contributing_file]: https://github.com/fewlinesco/connect-account/blob/master/README.adoc

2021-06-07 11:54 UTC, frieda-ewlines commented
Task linked: [CU-m36f49 [POC] - I18n](https://app.clickup.com/t/m36f49)

2021-06-17 07:53 UTC, Oluane commented on content/locales/fr.ts
> +      "Gérez vos options de connexion, y compris les courriels, les numéros de téléphone et les comptes sociales",
```suggestion
      "Gérez vos options de connexion, y compris les courriels, les numéros de téléphone et les comptes sociaux",
```

2021-06-17 07:53 UTC, Oluane commented on content/locales/fr.ts
> +    socialNoIdentityMessage: "Aucun compte sociale n’a encore été ajoutée",
```suggestion
    socialNoIdentityMessage: "Aucun compte social n’a encore été ajouté",
```

2021-06-17 08:01 UTC, Meyclem requested changes

2021-06-17 08:02 UTC, Fuzznimp commented on src/components/pages/locale/locale.tsx
> +              router && router.push("/account", undefined, { locale });
It is an alias for the URL (name `as`). They did not overload the function, so you need to pass `URL | undefined` if you want to pass the options object.

2021-06-17 08:07 UTC, Fuzznimp commented on content/locales/fr.ts
> +    info: "Choisissez un moyen de contact ci-dessous que nous enverrons un code de validation à:",
Omg 🤣

2021-06-17 12:53 UTC, Meyclem submitted a review, later dismissed

2021-06-21 08:04 UTC, Oluane approved these changes

2021-06-21 08:05 UTC, merged