Localization of errors and fallback components
fewlinesco/connect-account pull request #741
Opened 2021-06-28 11:33 UTC by Fuzznimp

## Description

This PR adds some localization for the errors messages and fallback components.

## Type of change

- [x] **Chore** (non-breaking change which refactors / improves the existing code base).
- [ ] **Bug fix** (non-breaking change which fixes an issue).
- [ ] **New feature** (non-breaking change which adds functionality).
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected).

## Checklist

- [x] My code follows the style [**contributing guidelines**][contributing_file] of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.

[contributing_file]: https://github.com/fewlinesco/connect-account/blob/master/README.adoc

2021-06-28 11:33 UTC, frieda-ewlines commented
Task linked: [CU-9kywbh [feature] - Localize errors and fallback components](https://app.clickup.com/t/9kywbh)

2021-06-29 13:43 UTC, Oluane commented on content/locales/fr.ts
> +    homepage: "page d'acceuil.",
```suggestion
    homepage: "page d'accueil.",
```

2021-06-29 13:44 UTC, Oluane commented on content/locales/fr.ts
> +    passwordInfo: "Assurez-vous que votre mot de passe contient au moins :",
```suggestion
    passwordInfo: "Assurez-vous que votre mot de passe contienne au moins :",
```

2021-06-29 14:03 UTC, Meyclem requested changes

2021-06-29 14:03 UTC, Meyclem commented on content/locales/fr.ts
> +      "Le mot de passe que vous entrez ne répond pas aux critères.",
```suggestion
      "Le mot de passe saisi ne répond pas aux critères.",
```

2021-06-29 14:03 UTC, Meyclem commented on content/locales/en.ts
> +    passwordCriteria: "The password you enter does not meet the criteria.",
```suggestion
    passwordCriteria: "The password you entered does not meet the criteria.",
```

2021-06-29 14:23 UTC, Meyclem approved these changes

2021-06-29 14:31 UTC, merged